name: Smart Merge (Cherry-pick Non-Empty Commits)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  smart_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Fetch main
        run: git fetch origin main

      - name: Create temp branch from main
        run: |
          git checkout -B tmp-smart-merge origin/main

      - name: Cherry-pick non-empty commits from PR
        run: |
          PR_COMMITS=$(git rev-list --reverse origin/main..origin/${{ github.head_ref }})
          for COMMIT in $PR_COMMITS; do
            if [ "$(git show --pretty="" --name-only $COMMIT | wc -l)" -gt 0 ]; then
              echo "✅ Cherry-picking $COMMIT"
              git cherry-pick $COMMIT
            else
              echo "⏭️ Skipping empty commit $COMMIT"
            fi
          done

      - name: Push changes to main
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin tmp-smart-merge:main
